### ISSUE TITLE
Is forall a map?

### ISSUE THREAD

**Issue by hadley** [hedgehogqa/r-hedgehog#5]
If so, it might be worth considering a map2, and thinking about how to work around the verbosity of R's anonymous functions.

e.g.

```R
forall( gen.df, function(x) expect_equal(nrow(x), 1))
```

could be rewritten as:

```R
gen_df %>%
  gen_map(nrow) %>%
  for_all(expect_equal, 1)
```

And 

```R
forall(list(a = gen_element(1:100), b = gen_element(1:100)), function(a, b) expect_lt( a, b + 1 ))
```

as 

```R
a <- gen_element(1:100)
b <- gen_element(1:100) %>% gen_map(~ . + 1)

for_all2(a, b, expect_lt)
```

Note the use of the formula - see `purrr::as_function()` for details

**Comment by HuwCampbell** [comment]
Ok. So at the moment, a list of generators "is" a generator of lists, with a heuristic on whether to curry the function arguments (use `do.call` more or less).

Would something like
```r
forall <- function(..., property)
```
where the `...` can be named or unnamed generators make sense instead of varying arity suffixes. That should handle the second case pretty well.

I'll play around with using hedgehog with the piping operator more to see how the first example can be done.

Thanks for the input :)

**Comment by HuwCampbell** [comment]
Hmm. Maybe that would be a bit clunky as one would need to write `property = x`.

**Comment by HuwCampbell** [comment]
By map2 I believe you mean what haskellers would call a zip.

I don't think this is the case actually.
